# Generated by Django 5.1.1 on 2024-11-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
