# Generated by Django 5.1.1 on 2024-11-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_rename_service_price_surveyor_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyor',
            name='first_name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyor',
            name='last_name',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
