# Generated by Django 5.1.1 on 2024-11-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_surveyor_first_name_surveyor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
