# Generated by Django 5.1.1 on 2024-11-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('realestate', '0007_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='seller_or_surveyor',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seller_or_surveyor_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seller_or_surveyor_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
    ]
