# Generated by Django 5.1.1 on 2024-11-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('realestate', '0008_remove_chatroom_seller_or_surveyor_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('buyer', 'seller_or_surveyor_type', 'seller_or_surveyor_id')},
        ),
    ]
