# Generated by Django 5.1.1 on 2024-11-24 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_chatrooms', to='realestate.seller'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_chatrooms', to='realestate.surveyor'),
        ),
        migrations.AddField(
            model_name='message',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='realestate.seller'),
        ),
        migrations.AddField(
            model_name='message',
            name='surveyor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_surveyor', to='realestate.surveyor'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='seller_or_surveyor_id',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='seller_or_surveyor_type',
        ),
    ]
