# Generated by Django 5.1.1 on 2025-04-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0012_rename_created_at_chatroom_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='realestate.chatroom'),
        ),
    ]
