# Generated by Django 5.1.1 on 2025-04-18 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0013_alter_message_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realestate.seller'),
        ),
        migrations.DeleteModel(
            name='LandListing',
        ),
    ]
