# Generated by Django 5.1.1 on 2025-04-19 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0014_land_seller_delete_landlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='realestate.seller'),
        ),
    ]
